/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pbc-registry.proto */

#ifndef PROTOBUF_C_pbc_2dregistry_2eproto__INCLUDED
#define PROTOBUF_C_pbc_2dregistry_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PbcRegistryReq PbcRegistryReq;
typedef struct _PbcRegistryRsp PbcRegistryRsp;


/* --- enums --- */


/* --- messages --- */

struct  _PbcRegistryReq
{
  ProtobufCMessage base;
  uint32_t sid;
  char *name;
  char *system;
  char *location;
  uint64_t bandwidth;
  char *ip;
  uint32_t port;
};
#define PBC_REGISTRY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pbc_registry_req__descriptor) \
    , 0, NULL, NULL, NULL, 0, NULL, 0 }


struct  _PbcRegistryRsp
{
  ProtobufCMessage base;
  uint32_t sid;
  char *name;
  char *ip;
  protobuf_c_boolean has_num;
  uint32_t num;
};
#define PBC_REGISTRY_RSP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pbc_registry_rsp__descriptor) \
    , 0, NULL, NULL, 0, 0 }


/* PbcRegistryReq methods */
void   pbc_registry_req__init
                     (PbcRegistryReq         *message);
size_t pbc_registry_req__get_packed_size
                     (const PbcRegistryReq   *message);
size_t pbc_registry_req__pack
                     (const PbcRegistryReq   *message,
                      uint8_t             *out);
size_t pbc_registry_req__pack_to_buffer
                     (const PbcRegistryReq   *message,
                      ProtobufCBuffer     *buffer);
PbcRegistryReq *
       pbc_registry_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pbc_registry_req__free_unpacked
                     (PbcRegistryReq *message,
                      ProtobufCAllocator *allocator);
/* PbcRegistryRsp methods */
void   pbc_registry_rsp__init
                     (PbcRegistryRsp         *message);
size_t pbc_registry_rsp__get_packed_size
                     (const PbcRegistryRsp   *message);
size_t pbc_registry_rsp__pack
                     (const PbcRegistryRsp   *message,
                      uint8_t             *out);
size_t pbc_registry_rsp__pack_to_buffer
                     (const PbcRegistryRsp   *message,
                      ProtobufCBuffer     *buffer);
PbcRegistryRsp *
       pbc_registry_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pbc_registry_rsp__free_unpacked
                     (PbcRegistryRsp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PbcRegistryReq_Closure)
                 (const PbcRegistryReq *message,
                  void *closure_data);
typedef void (*PbcRegistryRsp_Closure)
                 (const PbcRegistryRsp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pbc_registry_req__descriptor;
extern const ProtobufCMessageDescriptor pbc_registry_rsp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pbc_2dregistry_2eproto__INCLUDED */
