/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pbc-vmon.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pbc-vmon.pb-c.h"
void   pbc_vmon_req__init
                     (PbcVmonReq         *message)
{
  static const PbcVmonReq init_value = PBC_VMON_REQ__INIT;
  *message = init_value;
}
size_t pbc_vmon_req__get_packed_size
                     (const PbcVmonReq *message)
{
  assert(message->base.descriptor == &pbc_vmon_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_vmon_req__pack
                     (const PbcVmonReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_vmon_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_vmon_req__pack_to_buffer
                     (const PbcVmonReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_vmon_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcVmonReq *
       pbc_vmon_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcVmonReq *)
     protobuf_c_message_unpack (&pbc_vmon_req__descriptor,
                                allocator, len, data);
}
void   pbc_vmon_req__free_unpacked
                     (PbcVmonReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_vmon_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pbc_vmon_rsp__init
                     (PbcVmonRsp         *message)
{
  static const PbcVmonRsp init_value = PBC_VMON_RSP__INIT;
  *message = init_value;
}
size_t pbc_vmon_rsp__get_packed_size
                     (const PbcVmonRsp *message)
{
  assert(message->base.descriptor == &pbc_vmon_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_vmon_rsp__pack
                     (const PbcVmonRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_vmon_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_vmon_rsp__pack_to_buffer
                     (const PbcVmonRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_vmon_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcVmonRsp *
       pbc_vmon_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcVmonRsp *)
     protobuf_c_message_unpack (&pbc_vmon_rsp__descriptor,
                                allocator, len, data);
}
void   pbc_vmon_rsp__free_unpacked
                     (PbcVmonRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_vmon_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pbc_vmon_req__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcVmonReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_vmon_req__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pbc_vmon_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pbc_vmon_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.VmonReq",
  "VmonReq",
  "PbcVmonReq",
  "pbc",
  sizeof(PbcVmonReq),
  1,
  pbc_vmon_req__field_descriptors,
  pbc_vmon_req__field_indices_by_name,
  1,  pbc_vmon_req__number_ranges,
  (ProtobufCMessageInit) pbc_vmon_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pbc_vmon_rsp__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcVmonRsp, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcVmonRsp, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_vmon_rsp__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pbc_vmon_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pbc_vmon_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.VmonRsp",
  "VmonRsp",
  "PbcVmonRsp",
  "pbc",
  sizeof(PbcVmonRsp),
  2,
  pbc_vmon_rsp__field_descriptors,
  pbc_vmon_rsp__field_indices_by_name,
  1,  pbc_vmon_rsp__number_ranges,
  (ProtobufCMessageInit) pbc_vmon_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
