/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pbc-nstatus.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pbc-nstatus.pb-c.h"
void   pbc_node_state_req__init
                     (PbcNodeStateReq         *message)
{
  static const PbcNodeStateReq init_value = PBC_NODE_STATE_REQ__INIT;
  *message = init_value;
}
size_t pbc_node_state_req__get_packed_size
                     (const PbcNodeStateReq *message)
{
  assert(message->base.descriptor == &pbc_node_state_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_node_state_req__pack
                     (const PbcNodeStateReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_node_state_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_node_state_req__pack_to_buffer
                     (const PbcNodeStateReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_node_state_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcNodeStateReq *
       pbc_node_state_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcNodeStateReq *)
     protobuf_c_message_unpack (&pbc_node_state_req__descriptor,
                                allocator, len, data);
}
void   pbc_node_state_req__free_unpacked
                     (PbcNodeStateReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_node_state_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pbc_node_state_rsp__init
                     (PbcNodeStateRsp         *message)
{
  static const PbcNodeStateRsp init_value = PBC_NODE_STATE_RSP__INIT;
  *message = init_value;
}
size_t pbc_node_state_rsp__get_packed_size
                     (const PbcNodeStateRsp *message)
{
  assert(message->base.descriptor == &pbc_node_state_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_node_state_rsp__pack
                     (const PbcNodeStateRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_node_state_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_node_state_rsp__pack_to_buffer
                     (const PbcNodeStateRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_node_state_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcNodeStateRsp *
       pbc_node_state_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcNodeStateRsp *)
     protobuf_c_message_unpack (&pbc_node_state_rsp__descriptor,
                                allocator, len, data);
}
void   pbc_node_state_rsp__free_unpacked
                     (PbcNodeStateRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_node_state_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pbc_node_state_req__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_node_state_req__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pbc_node_state_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pbc_node_state_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.NodeStateReq",
  "NodeStateReq",
  "PbcNodeStateReq",
  "pbc",
  sizeof(PbcNodeStateReq),
  1,
  pbc_node_state_req__field_descriptors,
  pbc_node_state_req__field_indices_by_name,
  1,  pbc_node_state_req__number_ranges,
  (ProtobufCMessageInit) pbc_node_state_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pbc_node_state_rsp__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uplink",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, uplink),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "downlink",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, downlink),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(PbcNodeStateRsp, cpu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_node_state_rsp__field_indices_by_name[] = {
  3,   /* field[3] = count */
  7,   /* field[7] = cpu */
  5,   /* field[5] = downlink */
  0,   /* field[0] = id */
  1,   /* field[1] = index */
  6,   /* field[6] = memory */
  2,   /* field[2] = name */
  4,   /* field[4] = uplink */
};
static const ProtobufCIntRange pbc_node_state_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor pbc_node_state_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.NodeStateRsp",
  "NodeStateRsp",
  "PbcNodeStateRsp",
  "pbc",
  sizeof(PbcNodeStateRsp),
  8,
  pbc_node_state_rsp__field_descriptors,
  pbc_node_state_rsp__field_indices_by_name,
  1,  pbc_node_state_rsp__number_ranges,
  (ProtobufCMessageInit) pbc_node_state_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
