/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pbc-demo.proto */

#ifndef PROTOBUF_C_pbc_2ddemo_2eproto__INCLUDED
#define PROTOBUF_C_pbc_2ddemo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PbcDemoReq PbcDemoReq;
typedef struct _PbcDemoRsp PbcDemoRsp;


/* --- enums --- */


/* --- messages --- */

struct  _PbcDemoReq
{
  ProtobufCMessage base;
  uint32_t id;
};
#define PBC_DEMO_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pbc_demo_req__descriptor) \
    , 0 }


struct  _PbcDemoRsp
{
  ProtobufCMessage base;
  uint32_t id;
  uint32_t video_cnt;
  uint64_t info_mem;
};
#define PBC_DEMO_RSP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pbc_demo_rsp__descriptor) \
    , 0, 0, 0 }


/* PbcDemoReq methods */
void   pbc_demo_req__init
                     (PbcDemoReq         *message);
size_t pbc_demo_req__get_packed_size
                     (const PbcDemoReq   *message);
size_t pbc_demo_req__pack
                     (const PbcDemoReq   *message,
                      uint8_t             *out);
size_t pbc_demo_req__pack_to_buffer
                     (const PbcDemoReq   *message,
                      ProtobufCBuffer     *buffer);
PbcDemoReq *
       pbc_demo_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pbc_demo_req__free_unpacked
                     (PbcDemoReq *message,
                      ProtobufCAllocator *allocator);
/* PbcDemoRsp methods */
void   pbc_demo_rsp__init
                     (PbcDemoRsp         *message);
size_t pbc_demo_rsp__get_packed_size
                     (const PbcDemoRsp   *message);
size_t pbc_demo_rsp__pack
                     (const PbcDemoRsp   *message,
                      uint8_t             *out);
size_t pbc_demo_rsp__pack_to_buffer
                     (const PbcDemoRsp   *message,
                      ProtobufCBuffer     *buffer);
PbcDemoRsp *
       pbc_demo_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pbc_demo_rsp__free_unpacked
                     (PbcDemoRsp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PbcDemoReq_Closure)
                 (const PbcDemoReq *message,
                  void *closure_data);
typedef void (*PbcDemoRsp_Closure)
                 (const PbcDemoRsp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pbc_demo_req__descriptor;
extern const ProtobufCMessageDescriptor pbc_demo_rsp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pbc_2ddemo_2eproto__INCLUDED */
