/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pbc-demo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pbc-demo.pb-c.h"
void   pbc_demo_req__init
                     (PbcDemoReq         *message)
{
  static const PbcDemoReq init_value = PBC_DEMO_REQ__INIT;
  *message = init_value;
}
size_t pbc_demo_req__get_packed_size
                     (const PbcDemoReq *message)
{
  assert(message->base.descriptor == &pbc_demo_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_demo_req__pack
                     (const PbcDemoReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_demo_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_demo_req__pack_to_buffer
                     (const PbcDemoReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_demo_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcDemoReq *
       pbc_demo_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcDemoReq *)
     protobuf_c_message_unpack (&pbc_demo_req__descriptor,
                                allocator, len, data);
}
void   pbc_demo_req__free_unpacked
                     (PbcDemoReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_demo_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pbc_demo_rsp__init
                     (PbcDemoRsp         *message)
{
  static const PbcDemoRsp init_value = PBC_DEMO_RSP__INIT;
  *message = init_value;
}
size_t pbc_demo_rsp__get_packed_size
                     (const PbcDemoRsp *message)
{
  assert(message->base.descriptor == &pbc_demo_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_demo_rsp__pack
                     (const PbcDemoRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_demo_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_demo_rsp__pack_to_buffer
                     (const PbcDemoRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_demo_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcDemoRsp *
       pbc_demo_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcDemoRsp *)
     protobuf_c_message_unpack (&pbc_demo_rsp__descriptor,
                                allocator, len, data);
}
void   pbc_demo_rsp__free_unpacked
                     (PbcDemoRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_demo_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pbc_demo_req__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcDemoReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_demo_req__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pbc_demo_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pbc_demo_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.DemoReq",
  "DemoReq",
  "PbcDemoReq",
  "pbc",
  sizeof(PbcDemoReq),
  1,
  pbc_demo_req__field_descriptors,
  pbc_demo_req__field_indices_by_name,
  1,  pbc_demo_req__number_ranges,
  (ProtobufCMessageInit) pbc_demo_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pbc_demo_rsp__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcDemoRsp, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_cnt",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcDemoRsp, video_cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info_mem",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbcDemoRsp, info_mem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_demo_rsp__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = info_mem */
  1,   /* field[1] = video_cnt */
};
static const ProtobufCIntRange pbc_demo_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pbc_demo_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.DemoRsp",
  "DemoRsp",
  "PbcDemoRsp",
  "pbc",
  sizeof(PbcDemoRsp),
  3,
  pbc_demo_rsp__field_descriptors,
  pbc_demo_rsp__field_indices_by_name,
  1,  pbc_demo_rsp__number_ranges,
  (ProtobufCMessageInit) pbc_demo_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
