/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pbc-registry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pbc-registry.pb-c.h"
void   pbc_registry_req__init
                     (PbcRegistryReq         *message)
{
  static const PbcRegistryReq init_value = PBC_REGISTRY_REQ__INIT;
  *message = init_value;
}
size_t pbc_registry_req__get_packed_size
                     (const PbcRegistryReq *message)
{
  assert(message->base.descriptor == &pbc_registry_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_registry_req__pack
                     (const PbcRegistryReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_registry_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_registry_req__pack_to_buffer
                     (const PbcRegistryReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_registry_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcRegistryReq *
       pbc_registry_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcRegistryReq *)
     protobuf_c_message_unpack (&pbc_registry_req__descriptor,
                                allocator, len, data);
}
void   pbc_registry_req__free_unpacked
                     (PbcRegistryReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_registry_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pbc_registry_rsp__init
                     (PbcRegistryRsp         *message)
{
  static const PbcRegistryRsp init_value = PBC_REGISTRY_RSP__INIT;
  *message = init_value;
}
size_t pbc_registry_rsp__get_packed_size
                     (const PbcRegistryRsp *message)
{
  assert(message->base.descriptor == &pbc_registry_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_registry_rsp__pack
                     (const PbcRegistryRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_registry_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_registry_rsp__pack_to_buffer
                     (const PbcRegistryRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_registry_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcRegistryRsp *
       pbc_registry_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcRegistryRsp *)
     protobuf_c_message_unpack (&pbc_registry_rsp__descriptor,
                                allocator, len, data);
}
void   pbc_registry_rsp__free_unpacked
                     (PbcRegistryRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_registry_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pbc_registry_req__field_descriptors[9] =
{
  {
    "sid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, system),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, location),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processor",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, processor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, memory),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryReq, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_registry_req__field_indices_by_name[] = {
  5,   /* field[5] = bandwidth */
  7,   /* field[7] = ip */
  3,   /* field[3] = location */
  6,   /* field[6] = memory */
  1,   /* field[1] = name */
  8,   /* field[8] = port */
  4,   /* field[4] = processor */
  0,   /* field[0] = sid */
  2,   /* field[2] = system */
};
static const ProtobufCIntRange pbc_registry_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor pbc_registry_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.RegistryReq",
  "RegistryReq",
  "PbcRegistryReq",
  "pbc",
  sizeof(PbcRegistryReq),
  9,
  pbc_registry_req__field_descriptors,
  pbc_registry_req__field_indices_by_name,
  1,  pbc_registry_req__number_ranges,
  (ProtobufCMessageInit) pbc_registry_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pbc_registry_rsp__field_descriptors[4] =
{
  {
    "sid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryRsp, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryRsp, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcRegistryRsp, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PbcRegistryRsp, has_num),
    offsetof(PbcRegistryRsp, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_registry_rsp__field_indices_by_name[] = {
  2,   /* field[2] = index */
  1,   /* field[1] = name */
  3,   /* field[3] = num */
  0,   /* field[0] = sid */
};
static const ProtobufCIntRange pbc_registry_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pbc_registry_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.RegistryRsp",
  "RegistryRsp",
  "PbcRegistryRsp",
  "pbc",
  sizeof(PbcRegistryRsp),
  4,
  pbc_registry_rsp__field_descriptors,
  pbc_registry_rsp__field_indices_by_name,
  1,  pbc_registry_rsp__number_ranges,
  (ProtobufCMessageInit) pbc_registry_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
