/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: workload.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "workload.pb-c.h"
void   pbc_workload_req__init
                     (PbcWorkloadReq         *message)
{
  static const PbcWorkloadReq init_value = PBC_WORKLOAD_REQ__INIT;
  *message = init_value;
}
size_t pbc_workload_req__get_packed_size
                     (const PbcWorkloadReq *message)
{
  assert(message->base.descriptor == &pbc_workload_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_workload_req__pack
                     (const PbcWorkloadReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_workload_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_workload_req__pack_to_buffer
                     (const PbcWorkloadReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_workload_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcWorkloadReq *
       pbc_workload_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcWorkloadReq *)
     protobuf_c_message_unpack (&pbc_workload_req__descriptor,
                                allocator, len, data);
}
void   pbc_workload_req__free_unpacked
                     (PbcWorkloadReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_workload_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pbc_workload_rsp__init
                     (PbcWorkloadRsp         *message)
{
  static const PbcWorkloadRsp init_value = PBC_WORKLOAD_RSP__INIT;
  *message = init_value;
}
size_t pbc_workload_rsp__get_packed_size
                     (const PbcWorkloadRsp *message)
{
  assert(message->base.descriptor == &pbc_workload_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbc_workload_rsp__pack
                     (const PbcWorkloadRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbc_workload_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbc_workload_rsp__pack_to_buffer
                     (const PbcWorkloadRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbc_workload_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbcWorkloadRsp *
       pbc_workload_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbcWorkloadRsp *)
     protobuf_c_message_unpack (&pbc_workload_rsp__descriptor,
                                allocator, len, data);
}
void   pbc_workload_rsp__free_unpacked
                     (PbcWorkloadRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pbc_workload_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pbc_workload_req__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcWorkloadReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_workload_req__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange pbc_workload_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pbc_workload_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.WorkloadReq",
  "WorkloadReq",
  "PbcWorkloadReq",
  "pbc",
  sizeof(PbcWorkloadReq),
  1,
  pbc_workload_req__field_descriptors,
  pbc_workload_req__field_indices_by_name,
  1,  pbc_workload_req__number_ranges,
  (ProtobufCMessageInit) pbc_workload_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pbc_workload_rsp__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcWorkloadRsp, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_cnt",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbcWorkloadRsp, video_cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info_mem",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PbcWorkloadRsp, info_mem),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbc_workload_rsp__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = info_mem */
  1,   /* field[1] = video_cnt */
};
static const ProtobufCIntRange pbc_workload_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pbc_workload_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbc.WorkloadRsp",
  "WorkloadRsp",
  "PbcWorkloadRsp",
  "pbc",
  sizeof(PbcWorkloadRsp),
  3,
  pbc_workload_rsp__field_descriptors,
  pbc_workload_rsp__field_indices_by_name,
  1,  pbc_workload_rsp__number_ranges,
  (ProtobufCMessageInit) pbc_workload_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
